const Data = [
    {
        id: 1,
        category: "education",
        year: "Oct 2023 - present",
        title: "Proclamation 45 University",
        major: 'Information Technology',
        degree: "Bachelor's degree",
        location: 'Yogyakarta, ID',
        desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
        id: 2,
        category: "education",
        year: "Aug 2019 - 2022 Jun",
        location: 'Center Java, ID',
        major: 'Software Engineering',
        degree: 'High-school degree',
        title: "Vocational 2 Karanganyar",
        duration: '3 years',
        desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
        id: 3,
        category: "experience",
        year: "Jul 2022 - Present",
        location: 'Yogyakarta, ID',
        company: "Lumut.id",
        position: 'Full-stack Developer',
        duration: '2 years',
        desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
    {
        id: 4,
        category: "experience",
        year: "Sep 2021 - Des 2021",
        location: 'Solo, ID',
        company: "Internet Marketing",
        position: 'Property Sales Designer',
        duration: '3 months',
        desc: "Lorem ipsum dolor sit amet quo ei simul congue exerci     ad nec admodum perfecto.",
    },
];
export default Data